### ISSUE TITLE
RuntimeInvoke with parameters and returns

### ISSUE THREAD

**Issue by HallMaru** [EquiFox/MInject#2]
Hi EquiFox, there is some way to call RuntimeInvoke(); with parameters and processing it result?

**Comment by EquiFox** [comment]
Hi @HallMaru !

Yes it is possible however my library doesn't support it. I'll look into it !

**Comment by HallMaru** [comment]
Hi @EquiFox, thank you for your reply, here is my source:
![image](https://user-images.githubusercontent.com/17103737/33520219-aa925d52-d79d-11e7-840f-fcf538ff2db8.png)
I`m trying to reproduce this:
![image](https://user-images.githubusercontent.com/17103737/33520228-cadb2cec-d79d-11e7-904d-c29ab4bb7f17.png)
 But i'm getting a Access Violation on run this.

**Comment by EquiFox** [comment]
After doing some tests, I'm having a hard time passing method arguments from our process to target process. It might works for basic types but as soon as we get objects (except strings) it crashes.

My suggestion is to inject a managed library and call it's entry point (static, no params) with MInject.
The library will run inside target process, thus allowing us to use reflection to call wanted method.

**Comment by HallMaru** [comment]
I`m trying to do with only basic types, do you have a example that works with a method with only one int parameter?

**Comment by EquiFox** [comment]
Look at mono_runtime_invoke_array instead

Also may I ask in what scenario you must directly call the method like this instead of injecting than calling it with reflection ?

**Comment by HallMaru** [comment]
Hi, i`ll try use mono_runtime_invoke_array.
I'm trying to do direct calls, because some functions is not working using this injection system (GetTypes() for example) and of course, to do some research and fun :P
